//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 05:04:50 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ������ ���������� �� ����� ���������
 *
 * <p>Java class for CashContributionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CashContributionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://directbank.1c.ru/XMLSchema}OtherPaymentDataType">
 *       &lt;sequence>
 *         &lt;element name="Person" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FullName" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IdentityDocument" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Symbol" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Source" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CashContributionType", propOrder = {
        "person",
        "symbol",
        "source"
})
public class CashContributionType
        extends OtherPaymentDataType {

    @XmlElement(name = "Person")
    protected CashContributionType.Person person;
    @XmlElement(name = "Symbol")
    protected String symbol;
    @XmlElement(name = "Source")
    protected String source;

    /**
     * Gets the value of the person property.
     *
     * @return possible object is
     * {@link CashContributionType.Person }
     */
    public CashContributionType.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     *
     * @param value allowed object is
     *              {@link CashContributionType.Person }
     */
    public void setPerson(CashContributionType.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the symbol property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSource(String value) {
        this.source = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FullName" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IdentityDocument" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "fullName",
            "identityDocument"
    })
    public static class Person {

        @XmlElement(name = "FullName")
        protected String fullName;
        @XmlElement(name = "IdentityDocument")
        protected String identityDocument;

        /**
         * Gets the value of the fullName property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the identityDocument property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIdentityDocument() {
            return identityDocument;
        }

        /**
         * Sets the value of the identityDocument property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIdentityDocument(String value) {
            this.identityDocument = value;
        }

    }

}
