//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 05:04:50 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * ������ ��������� ����
 *
 * <p>Java class for CheckType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CheckType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://directbank.1c.ru/XMLSchema}OtherPaymentDataType">
 *       &lt;sequence>
 *         &lt;element name="Person" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FullName" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IdentityDocument" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataPrinting" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CheckSeries" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CheckNumber" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Details" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Symbol">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Purpose" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Sum" type="{http://directbank.1c.ru/XMLSchema}SumType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckType", propOrder = {
        "person",
        "dataPrinting",
        "details"
})
public class CheckType
        extends OtherPaymentDataType {

    @XmlElement(name = "Person")
    protected CheckType.Person person;
    @XmlElement(name = "DataPrinting")
    protected CheckType.DataPrinting dataPrinting;
    @XmlElement(name = "Details")
    protected List<CheckType.Details> details;

    /**
     * Gets the value of the person property.
     *
     * @return possible object is
     * {@link CheckType.Person }
     */
    public CheckType.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     *
     * @param value allowed object is
     *              {@link CheckType.Person }
     */
    public void setPerson(CheckType.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the dataPrinting property.
     *
     * @return possible object is
     * {@link CheckType.DataPrinting }
     */
    public CheckType.DataPrinting getDataPrinting() {
        return dataPrinting;
    }

    /**
     * Sets the value of the dataPrinting property.
     *
     * @param value allowed object is
     *              {@link CheckType.DataPrinting }
     */
    public void setDataPrinting(CheckType.DataPrinting value) {
        this.dataPrinting = value;
    }

    /**
     * Gets the value of the details property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the details property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetails().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CheckType.Details }
     */
    public List<CheckType.Details> getDetails() {
        if (details == null) {
            details = new ArrayList<CheckType.Details>();
        }
        return this.details;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CheckSeries" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CheckNumber" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "checkSeries",
            "checkNumber"
    })
    public static class DataPrinting {

        @XmlElement(name = "CheckSeries")
        protected String checkSeries;
        @XmlElement(name = "CheckNumber")
        protected String checkNumber;

        /**
         * Gets the value of the checkSeries property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCheckSeries() {
            return checkSeries;
        }

        /**
         * Sets the value of the checkSeries property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCheckSeries(String value) {
            this.checkSeries = value;
        }

        /**
         * Gets the value of the checkNumber property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCheckNumber() {
            return checkNumber;
        }

        /**
         * Sets the value of the checkNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCheckNumber(String value) {
            this.checkNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Symbol">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Purpose" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Sum" type="{http://directbank.1c.ru/XMLSchema}SumType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "symbol",
            "purpose",
            "sum"
    })
    public static class Details {

        @XmlElement(name = "Symbol", required = true)
        protected String symbol;
        @XmlElement(name = "Purpose")
        protected String purpose;
        @XmlElement(name = "Sum", required = true)
        protected BigDecimal sum;

        /**
         * Gets the value of the symbol property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getSymbol() {
            return symbol;
        }

        /**
         * Sets the value of the symbol property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSymbol(String value) {
            this.symbol = value;
        }

        /**
         * Gets the value of the purpose property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPurpose() {
            return purpose;
        }

        /**
         * Sets the value of the purpose property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPurpose(String value) {
            this.purpose = value;
        }

        /**
         * Gets the value of the sum property.
         *
         * @return possible object is
         * {@link BigDecimal }
         */
        public BigDecimal getSum() {
            return sum;
        }

        /**
         * Sets the value of the sum property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setSum(BigDecimal value) {
            this.sum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FullName" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IdentityDocument" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "fullName",
            "identityDocument"
    })
    public static class Person {

        @XmlElement(name = "FullName")
        protected String fullName;
        @XmlElement(name = "IdentityDocument")
        protected String identityDocument;

        /**
         * Gets the value of the fullName property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the identityDocument property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIdentityDocument() {
            return identityDocument;
        }

        /**
         * Sets the value of the identityDocument property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIdentityDocument(String value) {
            this.identityDocument = value;
        }

    }

}
