//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 02:20:56 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for LogonCertResponseType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LogonCertResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EncryptedSID">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogonCertResponseType", propOrder = {
        "encryptedSID"
})
public class LogonCertResponseType {

    @XmlElement(name = "EncryptedSID", required = true)
    protected LogonCertResponseType.EncryptedSID encryptedSID;

    /**
     * Gets the value of the encryptedSID property.
     *
     * @return possible object is
     * {@link LogonCertResponseType.EncryptedSID }
     */
    public LogonCertResponseType.EncryptedSID getEncryptedSID() {
        return encryptedSID;
    }

    /**
     * Sets the value of the encryptedSID property.
     *
     * @param value allowed object is
     *              {@link LogonCertResponseType.EncryptedSID }
     */
    public void setEncryptedSID(LogonCertResponseType.EncryptedSID value) {
        this.encryptedSID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class EncryptedSID {

        @XmlValue
        protected byte[] value;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is
         * byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is
         *              byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

    }

}
