//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 02:20:56 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LogonResponseType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LogonResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SID" type="{http://directbank.1c.ru/XMLSchema}IDType"/>
 *         &lt;element name="ExtraAuth" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="OTP">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="phoneMask">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;maxLength value="12"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="code">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;maxLength value="10"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogonResponseType", propOrder = {
        "sid",
        "extraAuth"
})
public class LogonResponseType {

    @XmlElement(name = "SID", required = true)
    protected String sid;
    @XmlElement(name = "ExtraAuth")
    protected LogonResponseType.ExtraAuth extraAuth;

    /**
     * Gets the value of the sid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSID() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSID(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the extraAuth property.
     *
     * @return possible object is
     * {@link LogonResponseType.ExtraAuth }
     */
    public LogonResponseType.ExtraAuth getExtraAuth() {
        return extraAuth;
    }

    /**
     * Sets the value of the extraAuth property.
     *
     * @param value allowed object is
     *              {@link LogonResponseType.ExtraAuth }
     */
    public void setExtraAuth(LogonResponseType.ExtraAuth value) {
        this.extraAuth = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="OTP">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="phoneMask">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;maxLength value="12"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="code">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;maxLength value="10"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "otp"
    })
    public static class ExtraAuth {

        @XmlElement(name = "OTP")
        protected LogonResponseType.ExtraAuth.OTP otp;

        /**
         * Gets the value of the otp property.
         *
         * @return possible object is
         * {@link LogonResponseType.ExtraAuth.OTP }
         */
        public LogonResponseType.ExtraAuth.OTP getOTP() {
            return otp;
        }

        /**
         * Sets the value of the otp property.
         *
         * @param value allowed object is
         *              {@link LogonResponseType.ExtraAuth.OTP }
         */
        public void setOTP(LogonResponseType.ExtraAuth.OTP value) {
            this.otp = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="phoneMask">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;maxLength value="12"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="code">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;maxLength value="10"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class OTP {

            @XmlAttribute(name = "phoneMask")
            protected String phoneMask;
            @XmlAttribute(name = "code")
            protected String code;

            /**
             * Gets the value of the phoneMask property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPhoneMask() {
                return phoneMask;
            }

            /**
             * Sets the value of the phoneMask property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPhoneMask(String value) {
                this.phoneMask = value;
            }

            /**
             * Gets the value of the code property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setCode(String value) {
                this.code = value;
            }

        }

    }

}
