//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 05:04:50 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the xsd.types package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Packet_QNAME = new QName("http://directbank.1c.ru/XMLSchema", "Packet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xsd.types
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigestType }
     */
    public DigestType createDigestType() {
        return new DigestType();
    }

    /**
     * Create an instance of {@link CheckType }
     */
    public CheckType createCheckType() {
        return new CheckType();
    }

    /**
     * Create an instance of {@link DocumentType }
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link MemOrderApp }
     */
    public MemOrderApp createMemOrderApp() {
        return new MemOrderApp();
    }

    /**
     * Create an instance of {@link CashContributionType }
     */
    public CashContributionType createCashContributionType() {
        return new CashContributionType();
    }

    /**
     * Create an instance of {@link Packet }
     */
    public Packet createPacket() {
        return new Packet();
    }

    /**
     * Create an instance of {@link CollectionOrderApp }
     */
    public CollectionOrderApp createCollectionOrderApp() {
        return new CollectionOrderApp();
    }

    /**
     * Create an instance of {@link BankPartyType }
     */
    public BankPartyType createBankPartyType() {
        return new BankPartyType();
    }

    /**
     * Create an instance of {@link OtherPaymentDataType }
     */
    public OtherPaymentDataType createOtherPaymentDataType() {
        return new OtherPaymentDataType();
    }

    /**
     * Create an instance of {@link OtherCustomerDetailsType }
     */
    public OtherCustomerDetailsType createOtherCustomerDetailsType() {
        return new OtherCustomerDetailsType();
    }

    /**
     * Create an instance of {@link ResultStatusType }
     */
    public ResultStatusType createResultStatusType() {
        return new ResultStatusType();
    }

    /**
     * Create an instance of {@link ErrorType }
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link PaymentOrderApp }
     */
    public PaymentOrderApp createPaymentOrderApp() {
        return new PaymentOrderApp();
    }

    /**
     * Create an instance of {@link ParticipantType }
     */
    public ParticipantType createParticipantType() {
        return new ParticipantType();
    }

    /**
     * Create an instance of {@link PayRequestApp }
     */
    public PayRequestApp createPayRequestApp() {
        return new PayRequestApp();
    }

    /**
     * Create an instance of {@link PayDocRuApp }
     */
    public PayDocRuApp createPayDocRuApp() {
        return new PayDocRuApp();
    }

    /**
     * Create an instance of {@link BankOrderApp }
     */
    public BankOrderApp createBankOrderApp() {
        return new BankOrderApp();
    }

    /**
     * Create an instance of {@link CustomerPartyType }
     */
    public CustomerPartyType createCustomerPartyType() {
        return new CustomerPartyType();
    }

    /**
     * Create an instance of {@link CustomerDetailsType }
     */
    public CustomerDetailsType createCustomerDetailsType() {
        return new CustomerDetailsType();
    }

    /**
     * Create an instance of {@link StatusType }
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link BudgetPaymentInfoType }
     */
    public BudgetPaymentInfoType createBudgetPaymentInfoType() {
        return new BudgetPaymentInfoType();
    }

    /**
     * Create an instance of {@link BankType }
     */
    public BankType createBankType() {
        return new BankType();
    }

    /**
     * Create an instance of {@link PaymentDataType }
     */
    public PaymentDataType createPaymentDataType() {
        return new PaymentDataType();
    }

    /**
     * Create an instance of {@link DigestType.Data }
     */
    public DigestType.Data createDigestTypeData() {
        return new DigestType.Data();
    }

    /**
     * Create an instance of {@link CheckType.Person }
     */
    public CheckType.Person createCheckTypePerson() {
        return new CheckType.Person();
    }

    /**
     * Create an instance of {@link CheckType.DataPrinting }
     */
    public CheckType.DataPrinting createCheckTypeDataPrinting() {
        return new CheckType.DataPrinting();
    }

    /**
     * Create an instance of {@link CheckType.Details }
     */
    public CheckType.Details createCheckTypeDetails() {
        return new CheckType.Details();
    }

    /**
     * Create an instance of {@link DocumentType.Data }
     */
    public DocumentType.Data createDocumentTypeData() {
        return new DocumentType.Data();
    }

    /**
     * Create an instance of {@link DocumentType.Signature }
     */
    public DocumentType.Signature createDocumentTypeSignature() {
        return new DocumentType.Signature();
    }

    /**
     * Create an instance of {@link MemOrderApp.Author }
     */
    public MemOrderApp.Author createMemOrderAppAuthor() {
        return new MemOrderApp.Author();
    }

    /**
     * Create an instance of {@link CashContributionType.Person }
     */
    public CashContributionType.Person createCashContributionTypePerson() {
        return new CashContributionType.Person();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Packet }{@code >}}
     */
    @XmlElementDecl(namespace = "http://directbank.1c.ru/XMLSchema", name = "Packet")
    public JAXBElement<Packet> createPacket(Packet value) {
        return new JAXBElement<Packet>(_Packet_QNAME, Packet.class, null, value);
    }

}
