//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 05:04:50 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;


/**
 * ��������� ���� ���������� ����������
 *
 * <p>Java class for OtherPaymentDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OtherPaymentDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DocDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Sum" type="{http://directbank.1c.ru/XMLSchema}SumType"/>
 *         &lt;element name="Payer" type="{http://directbank.1c.ru/XMLSchema}OtherCustomerDetailsType" minOccurs="0"/>
 *         &lt;element name="Payee" type="{http://directbank.1c.ru/XMLSchema}OtherCustomerDetailsType" minOccurs="0"/>
 *         &lt;element name="TransitionKind" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Code" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Purpose" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherPaymentDataType", propOrder = {
        "docNo",
        "docDate",
        "sum",
        "payer",
        "payee",
        "transitionKind",
        "code",
        "purpose"
})
@XmlSeeAlso({
        CashContributionType.class,
        CheckType.class
})
public class OtherPaymentDataType {

    @XmlElement(name = "DocNo")
    protected String docNo;
    @XmlElement(name = "DocDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar docDate;
    @XmlElement(name = "Sum", required = true)
    protected BigDecimal sum;
    @XmlElement(name = "Payer")
    protected OtherCustomerDetailsType payer;
    @XmlElement(name = "Payee")
    protected OtherCustomerDetailsType payee;
    @XmlElement(name = "TransitionKind")
    protected String transitionKind;
    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "Purpose")
    protected String purpose;

    /**
     * Gets the value of the docNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * Sets the value of the docNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocNo(String value) {
        this.docNo = value;
    }

    /**
     * Gets the value of the docDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDocDate() {
        return docDate;
    }

    /**
     * Sets the value of the docDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDocDate(XMLGregorianCalendar value) {
        this.docDate = value;
    }

    /**
     * Gets the value of the sum property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setSum(BigDecimal value) {
        this.sum = value;
    }

    /**
     * Gets the value of the payer property.
     *
     * @return possible object is
     * {@link OtherCustomerDetailsType }
     */
    public OtherCustomerDetailsType getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     *
     * @param value allowed object is
     *              {@link OtherCustomerDetailsType }
     */
    public void setPayer(OtherCustomerDetailsType value) {
        this.payer = value;
    }

    /**
     * Gets the value of the payee property.
     *
     * @return possible object is
     * {@link OtherCustomerDetailsType }
     */
    public OtherCustomerDetailsType getPayee() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     *
     * @param value allowed object is
     *              {@link OtherCustomerDetailsType }
     */
    public void setPayee(OtherCustomerDetailsType value) {
        this.payee = value;
    }

    /**
     * Gets the value of the transitionKind property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransitionKind() {
        return transitionKind;
    }

    /**
     * Sets the value of the transitionKind property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransitionKind(String value) {
        this.transitionKind = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the purpose property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

}
