//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 05:04:50 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Packet complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Packet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sender" type="{http://directbank.1c.ru/XMLSchema}ParticipantType"/>
 *         &lt;element name="Recipient" type="{http://directbank.1c.ru/XMLSchema}ParticipantType"/>
 *         &lt;element name="Document" type="{http://directbank.1c.ru/XMLSchema}DocumentType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://directbank.1c.ru/XMLSchema}IDType" />
 *       &lt;attribute name="formatVersion" use="required" type="{http://directbank.1c.ru/XMLSchema}FormatVersionType" />
 *       &lt;attribute name="creationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="userAgent" type="{http://directbank.1c.ru/XMLSchema}UserAgentType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Packet", propOrder = {
        "sender",
        "recipient",
        "document"
})
public class Packet {

    @XmlElement(name = "Sender", required = true)
    protected ParticipantType sender;
    @XmlElement(name = "Recipient", required = true)
    protected ParticipantType recipient;
    @XmlElement(name = "Document", required = true)
    protected List<DocumentType> document;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "formatVersion", required = true)
    protected String formatVersion;
    @XmlAttribute(name = "creationDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(name = "userAgent")
    protected String userAgent;

    /**
     * Gets the value of the sender property.
     *
     * @return possible object is
     * {@link ParticipantType }
     */
    public ParticipantType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value allowed object is
     *              {@link ParticipantType }
     */
    public void setSender(ParticipantType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the recipient property.
     *
     * @return possible object is
     * {@link ParticipantType }
     */
    public ParticipantType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     *
     * @param value allowed object is
     *              {@link ParticipantType }
     */
    public void setRecipient(ParticipantType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the document property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentType }
     */
    public List<DocumentType> getDocument() {
        if (document == null) {
            document = new ArrayList<DocumentType>();
        }
        return this.document;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the formatVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFormatVersion() {
        return formatVersion;
    }

    /**
     * Sets the value of the formatVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFormatVersion(String value) {
        this.formatVersion = value;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the userAgent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Sets the value of the userAgent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUserAgent(String value) {
        this.userAgent = value;
    }

}
