//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 05:04:50 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ���� �� ������, ����������� ������� � ������ ������������ ����������� (��������)
 *
 * <p>Java class for ParticipantType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ParticipantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Customer" type="{http://directbank.1c.ru/XMLSchema}CustomerPartyType"/>
 *         &lt;element name="Bank" type="{http://directbank.1c.ru/XMLSchema}BankPartyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParticipantType", propOrder = {
        "customer",
        "bank"
})
public class ParticipantType {

    @XmlElement(name = "Customer")
    protected CustomerPartyType customer;
    @XmlElement(name = "Bank")
    protected BankPartyType bank;

    /**
     * Gets the value of the customer property.
     *
     * @return possible object is
     * {@link CustomerPartyType }
     */
    public CustomerPartyType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     *
     * @param value allowed object is
     *              {@link CustomerPartyType }
     */
    public void setCustomer(CustomerPartyType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the bank property.
     *
     * @return possible object is
     * {@link BankPartyType }
     */
    public BankPartyType getBank() {
        return bank;
    }

    /**
     * Sets the value of the bank property.
     *
     * @param value allowed object is
     *              {@link BankPartyType }
     */
    public void setBank(BankPartyType value) {
        this.bank = value;
    }

}
