//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 05:04:50 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * ������ ���������� ������
 *
 * <p>Java class for PaymentOrderApp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PaymentOrderApp">
 *   &lt;complexContent>
 *     &lt;extension base="{http://directbank.1c.ru/XMLSchema}PaymentDataType">
 *       &lt;sequence>
 *         &lt;element name="TransitionContent" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PartialPaymentNo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PartialTransitionKind" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SumResidualPayment" type="{http://directbank.1c.ru/XMLSchema}SumType" minOccurs="0"/>
 *         &lt;element name="PartialDocNo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PartialDocDate" type="{http://directbank.1c.ru/XMLSchema}DateString" minOccurs="0"/>
 *         &lt;element name="BudgetPaymentInfo" type="{http://directbank.1c.ru/XMLSchema}BudgetPaymentInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentOrderApp", propOrder = {
        "transitionContent",
        "partialPaymentNo",
        "partialTransitionKind",
        "sumResidualPayment",
        "partialDocNo",
        "partialDocDate",
        "budgetPaymentInfo"
})
public class PaymentOrderApp
        extends PaymentDataType {

    @XmlElement(name = "TransitionContent")
    protected String transitionContent;
    @XmlElement(name = "PartialPaymentNo")
    protected String partialPaymentNo;
    @XmlElement(name = "PartialTransitionKind")
    protected String partialTransitionKind;
    @XmlElement(name = "SumResidualPayment")
    protected BigDecimal sumResidualPayment;
    @XmlElement(name = "PartialDocNo")
    protected String partialDocNo;
    @XmlElement(name = "PartialDocDate")
    protected String partialDocDate;
    @XmlElement(name = "BudgetPaymentInfo")
    protected BudgetPaymentInfoType budgetPaymentInfo;

    /**
     * Gets the value of the transitionContent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransitionContent() {
        return transitionContent;
    }

    /**
     * Sets the value of the transitionContent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransitionContent(String value) {
        this.transitionContent = value;
    }

    /**
     * Gets the value of the partialPaymentNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPartialPaymentNo() {
        return partialPaymentNo;
    }

    /**
     * Sets the value of the partialPaymentNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPartialPaymentNo(String value) {
        this.partialPaymentNo = value;
    }

    /**
     * Gets the value of the partialTransitionKind property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPartialTransitionKind() {
        return partialTransitionKind;
    }

    /**
     * Sets the value of the partialTransitionKind property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPartialTransitionKind(String value) {
        this.partialTransitionKind = value;
    }

    /**
     * Gets the value of the sumResidualPayment property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getSumResidualPayment() {
        return sumResidualPayment;
    }

    /**
     * Sets the value of the sumResidualPayment property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setSumResidualPayment(BigDecimal value) {
        this.sumResidualPayment = value;
    }

    /**
     * Gets the value of the partialDocNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPartialDocNo() {
        return partialDocNo;
    }

    /**
     * Sets the value of the partialDocNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPartialDocNo(String value) {
        this.partialDocNo = value;
    }

    /**
     * Gets the value of the partialDocDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPartialDocDate() {
        return partialDocDate;
    }

    /**
     * Sets the value of the partialDocDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPartialDocDate(String value) {
        this.partialDocDate = value;
    }

    /**
     * Gets the value of the budgetPaymentInfo property.
     *
     * @return possible object is
     * {@link BudgetPaymentInfoType }
     */
    public BudgetPaymentInfoType getBudgetPaymentInfo() {
        return budgetPaymentInfo;
    }

    /**
     * Sets the value of the budgetPaymentInfo property.
     *
     * @param value allowed object is
     *              {@link BudgetPaymentInfoType }
     */
    public void setBudgetPaymentInfo(BudgetPaymentInfoType value) {
        this.budgetPaymentInfo = value;
    }

}
