//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 04:36:09 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ������-����
 *
 * <p>Java class for Probe complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Probe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sender" type="{http://directbank.1c.ru/XMLSchema}CustomerPartyType"/>
 *         &lt;element name="Recipient" type="{http://directbank.1c.ru/XMLSchema}BankPartyType"/>
 *         &lt;element name="Digest" type="{http://directbank.1c.ru/XMLSchema}DigestType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://directbank.1c.ru/XMLSchema}IDType" />
 *       &lt;attribute name="formatVersion" use="required" type="{http://directbank.1c.ru/XMLSchema}FormatVersionType" />
 *       &lt;attribute name="creationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="userAgent" type="{http://directbank.1c.ru/XMLSchema}UserAgentType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Probe", propOrder = {
        "sender",
        "recipient",
        "digest"
})
public class Probe {

    @XmlElement(name = "Sender", required = true)
    protected CustomerPartyType sender;
    @XmlElement(name = "Recipient", required = true)
    protected BankPartyType recipient;
    @XmlElement(name = "Digest")
    protected DigestType digest;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "formatVersion", required = true)
    protected String formatVersion;
    @XmlAttribute(name = "creationDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(name = "userAgent")
    protected String userAgent;

    /**
     * Gets the value of the sender property.
     *
     * @return possible object is
     * {@link CustomerPartyType }
     */
    public CustomerPartyType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value allowed object is
     *              {@link CustomerPartyType }
     */
    public void setSender(CustomerPartyType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the recipient property.
     *
     * @return possible object is
     * {@link BankPartyType }
     */
    public BankPartyType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     *
     * @param value allowed object is
     *              {@link BankPartyType }
     */
    public void setRecipient(BankPartyType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the digest property.
     *
     * @return possible object is
     * {@link DigestType }
     */
    public DigestType getDigest() {
        return digest;
    }

    /**
     * Sets the value of the digest property.
     *
     * @param value allowed object is
     *              {@link DigestType }
     */
    public void setDigest(DigestType value) {
        this.digest = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the formatVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFormatVersion() {
        return formatVersion;
    }

    /**
     * Sets the value of the formatVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFormatVersion(String value) {
        this.formatVersion = value;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the userAgent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Sets the value of the userAgent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUserAgent(String value) {
        this.userAgent = value;
    }

}
