//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 02:20:49 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * ��������� ������ ������� � ������
 * 
 * <p>Java class for Settings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Settings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sender" type="{http://directbank.1c.ru/XMLSchema}BankPartyType"/>
 *         &lt;element name="Recipient" type="{http://directbank.1c.ru/XMLSchema}CustomerPartyType"/>
 *         &lt;element name="Data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustomerID" type="{http://directbank.1c.ru/XMLSchema}IDCustomerType"/>
 *                   &lt;element name="BankServerAddress">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FormatVersion" type="{http://directbank.1c.ru/XMLSchema}FormatVersionType"/>
 *                   &lt;element name="Encoding">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="UTF-8"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Compress" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="Logon">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="Login">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="User">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="50"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Certificate">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="EncryptingAlgorithm">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="50"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CryptoParameters" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CSPName">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="256"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CSPType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="SignAlgorithm">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="HashAlgorithm">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;sequence>
 *                               &lt;element name="Encrypted" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="EncryptAlgorithm">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;maxLength value="50"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                             &lt;element name="BankTrustedRootCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                             &lt;element name="BankCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                             &lt;element name="CustomerSignature">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="GroupSignatures" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Certificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="9"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="numberGroup" use="required">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="URLAddinInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Document" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Signed" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RuleSignatures">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="docKind" use="required" type="{http://directbank.1c.ru/XMLSchema}DocKindType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ReceiptStatement" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Login">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Instructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://directbank.1c.ru/XMLSchema}IDType" />
 *       &lt;attribute name="formatVersion" use="required" type="{http://directbank.1c.ru/XMLSchema}FormatVersionType" />
 *       &lt;attribute name="creationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="userAgent" type="{http://directbank.1c.ru/XMLSchema}UserAgentType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Settings", propOrder = {
    "sender",
    "recipient",
    "data"
})
@XmlRootElement
public class Settings {

    @XmlElement(name = "Sender", required = true)
    protected BankPartyType sender;
    @XmlElement(name = "Recipient", required = true)
    protected CustomerPartyType recipient;
    @XmlElement(name = "Data", required = true)
    protected Settings.Data data;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "formatVersion", required = true)
    protected String formatVersion;
    @XmlAttribute(name = "creationDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(name = "userAgent")
    protected String userAgent;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link BankPartyType }
     *     
     */
    public BankPartyType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankPartyType }
     *     
     */
    public void setSender(BankPartyType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerPartyType }
     *     
     */
    public CustomerPartyType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerPartyType }
     *     
     */
    public void setRecipient(CustomerPartyType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Settings.Data }
     *     
     */
    public Settings.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings.Data }
     *     
     */
    public void setData(Settings.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the formatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatVersion() {
        return formatVersion;
    }

    /**
     * Sets the value of the formatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatVersion(String value) {
        this.formatVersion = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the userAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Sets the value of the userAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserAgent(String value) {
        this.userAgent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustomerID" type="{http://directbank.1c.ru/XMLSchema}IDCustomerType"/>
     *         &lt;element name="BankServerAddress">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FormatVersion" type="{http://directbank.1c.ru/XMLSchema}FormatVersionType"/>
     *         &lt;element name="Encoding">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="UTF-8"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Compress" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="Logon">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="Login">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="User">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="50"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Certificate">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="EncryptingAlgorithm">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="50"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CryptoParameters" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CSPName">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="256"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CSPType" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="SignAlgorithm">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="HashAlgorithm">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;sequence>
     *                     &lt;element name="Encrypted" minOccurs="0">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="EncryptAlgorithm">
     *                                 &lt;simpleType>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                     &lt;maxLength value="50"/>
     *                                   &lt;/restriction>
     *                                 &lt;/simpleType>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                   &lt;element name="BankTrustedRootCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
     *                   &lt;element name="BankCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
     *                   &lt;element name="CustomerSignature">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="GroupSignatures" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Certificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="9"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="numberGroup" use="required">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="URLAddinInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Document" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Signed" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RuleSignatures">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="docKind" use="required" type="{http://directbank.1c.ru/XMLSchema}DocKindType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ReceiptStatement" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Login">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Instructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerID",
        "bankServerAddress",
        "formatVersion",
        "encoding",
        "compress",
        "logon",
        "cryptoParameters",
        "document",
        "receiptStatement"
    })
    public static class Data {

        @XmlElement(name = "CustomerID", required = true)
        protected String customerID;
        @XmlElement(name = "BankServerAddress", required = true)
        protected String bankServerAddress;
        @XmlElement(name = "FormatVersion", required = true)
        protected String formatVersion;
        @XmlElement(name = "Encoding", required = true, defaultValue = "UTF-8")
        protected String encoding;
        @XmlElement(name = "Compress", defaultValue = "false")
        protected Boolean compress;
        @XmlElement(name = "Logon", required = true)
        protected Settings.Data.Logon logon;
        @XmlElement(name = "CryptoParameters")
        protected Settings.Data.CryptoParameters cryptoParameters;
        @XmlElement(name = "Document", required = true)
        protected List<Settings.Data.Document> document;
        @XmlElement(name = "ReceiptStatement")
        protected Settings.Data.ReceiptStatement receiptStatement;

        /**
         * Gets the value of the customerID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerID() {
            return customerID;
        }

        /**
         * Sets the value of the customerID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerID(String value) {
            this.customerID = value;
        }

        /**
         * Gets the value of the bankServerAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBankServerAddress() {
            return bankServerAddress;
        }

        /**
         * Sets the value of the bankServerAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBankServerAddress(String value) {
            this.bankServerAddress = value;
        }

        /**
         * Gets the value of the formatVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormatVersion() {
            return formatVersion;
        }

        /**
         * Sets the value of the formatVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormatVersion(String value) {
            this.formatVersion = value;
        }

        /**
         * Gets the value of the encoding property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEncoding() {
            return encoding;
        }

        /**
         * Sets the value of the encoding property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEncoding(String value) {
            this.encoding = value;
        }

        /**
         * Gets the value of the compress property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isCompress() {
            return compress;
        }

        /**
         * Sets the value of the compress property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCompress(Boolean value) {
            this.compress = value;
        }

        /**
         * Gets the value of the logon property.
         * 
         * @return
         *     possible object is
         *     {@link Settings.Data.Logon }
         *     
         */
        public Settings.Data.Logon getLogon() {
            return logon;
        }

        /**
         * Sets the value of the logon property.
         * 
         * @param value
         *     allowed object is
         *     {@link Settings.Data.Logon }
         *     
         */
        public void setLogon(Settings.Data.Logon value) {
            this.logon = value;
        }

        /**
         * Gets the value of the cryptoParameters property.
         * 
         * @return
         *     possible object is
         *     {@link Settings.Data.CryptoParameters }
         *     
         */
        public Settings.Data.CryptoParameters getCryptoParameters() {
            return cryptoParameters;
        }

        /**
         * Sets the value of the cryptoParameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Settings.Data.CryptoParameters }
         *     
         */
        public void setCryptoParameters(Settings.Data.CryptoParameters value) {
            this.cryptoParameters = value;
        }

        /**
         * Gets the value of the document property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the document property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Settings.Data.Document }
         * 
         * 
         */
        public List<Settings.Data.Document> getDocument() {
            if (document == null) {
                document = new ArrayList<Settings.Data.Document>();
            }
            return this.document;
        }

        /**
         * Gets the value of the receiptStatement property.
         * 
         * @return
         *     possible object is
         *     {@link Settings.Data.ReceiptStatement }
         *     
         */
        public Settings.Data.ReceiptStatement getReceiptStatement() {
            return receiptStatement;
        }

        /**
         * Sets the value of the receiptStatement property.
         * 
         * @param value
         *     allowed object is
         *     {@link Settings.Data.ReceiptStatement }
         *     
         */
        public void setReceiptStatement(Settings.Data.ReceiptStatement value) {
            this.receiptStatement = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CSPName">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="256"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CSPType" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="SignAlgorithm">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="HashAlgorithm">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;sequence>
         *           &lt;element name="Encrypted" minOccurs="0">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="EncryptAlgorithm">
         *                       &lt;simpleType>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                           &lt;maxLength value="50"/>
         *                         &lt;/restriction>
         *                       &lt;/simpleType>
         *                     &lt;/element>
         *                   &lt;/sequence>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *         &lt;/sequence>
         *         &lt;element name="BankTrustedRootCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
         *         &lt;element name="BankCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
         *         &lt;element name="CustomerSignature">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="GroupSignatures" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Certificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="9"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="numberGroup" use="required">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="URLAddinInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cspName",
            "cspType",
            "signAlgorithm",
            "hashAlgorithm",
            "encrypted",
            "bankTrustedRootCertificate",
            "bankCertificate",
            "customerSignature",
            "urlAddinInfo"
        })
        public static class CryptoParameters {

            @XmlElement(name = "CSPName", required = true)
            protected String cspName;
            @XmlElement(name = "CSPType")
            protected int cspType;
            @XmlElement(name = "SignAlgorithm", required = true)
            protected String signAlgorithm;
            @XmlElement(name = "HashAlgorithm", required = true)
            protected String hashAlgorithm;
            @XmlElement(name = "Encrypted")
            protected Settings.Data.CryptoParameters.Encrypted encrypted;
            @XmlElement(name = "BankTrustedRootCertificate")
            protected byte[] bankTrustedRootCertificate;
            @XmlElement(name = "BankCertificate")
            protected byte[] bankCertificate;
            @XmlElement(name = "CustomerSignature", required = true)
            protected Settings.Data.CryptoParameters.CustomerSignature customerSignature;
            @XmlElement(name = "URLAddinInfo")
            protected String urlAddinInfo;

            /**
             * Gets the value of the cspName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCSPName() {
                return cspName;
            }

            /**
             * Sets the value of the cspName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCSPName(String value) {
                this.cspName = value;
            }

            /**
             * Gets the value of the cspType property.
             * 
             */
            public int getCSPType() {
                return cspType;
            }

            /**
             * Sets the value of the cspType property.
             * 
             */
            public void setCSPType(int value) {
                this.cspType = value;
            }

            /**
             * Gets the value of the signAlgorithm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSignAlgorithm() {
                return signAlgorithm;
            }

            /**
             * Sets the value of the signAlgorithm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSignAlgorithm(String value) {
                this.signAlgorithm = value;
            }

            /**
             * Gets the value of the hashAlgorithm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHashAlgorithm() {
                return hashAlgorithm;
            }

            /**
             * Sets the value of the hashAlgorithm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHashAlgorithm(String value) {
                this.hashAlgorithm = value;
            }

            /**
             * Gets the value of the encrypted property.
             * 
             * @return
             *     possible object is
             *     {@link Settings.Data.CryptoParameters.Encrypted }
             *     
             */
            public Settings.Data.CryptoParameters.Encrypted getEncrypted() {
                return encrypted;
            }

            /**
             * Sets the value of the encrypted property.
             * 
             * @param value
             *     allowed object is
             *     {@link Settings.Data.CryptoParameters.Encrypted }
             *     
             */
            public void setEncrypted(Settings.Data.CryptoParameters.Encrypted value) {
                this.encrypted = value;
            }

            /**
             * Gets the value of the bankTrustedRootCertificate property.
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getBankTrustedRootCertificate() {
                return bankTrustedRootCertificate;
            }

            /**
             * Sets the value of the bankTrustedRootCertificate property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             */
            public void setBankTrustedRootCertificate(byte[] value) {
                this.bankTrustedRootCertificate = value;
            }

            /**
             * Gets the value of the bankCertificate property.
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getBankCertificate() {
                return bankCertificate;
            }

            /**
             * Sets the value of the bankCertificate property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             */
            public void setBankCertificate(byte[] value) {
                this.bankCertificate = value;
            }

            /**
             * Gets the value of the customerSignature property.
             * 
             * @return
             *     possible object is
             *     {@link Settings.Data.CryptoParameters.CustomerSignature }
             *     
             */
            public Settings.Data.CryptoParameters.CustomerSignature getCustomerSignature() {
                return customerSignature;
            }

            /**
             * Sets the value of the customerSignature property.
             * 
             * @param value
             *     allowed object is
             *     {@link Settings.Data.CryptoParameters.CustomerSignature }
             *     
             */
            public void setCustomerSignature(Settings.Data.CryptoParameters.CustomerSignature value) {
                this.customerSignature = value;
            }

            /**
             * Gets the value of the urlAddinInfo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getURLAddinInfo() {
                return urlAddinInfo;
            }

            /**
             * Sets the value of the urlAddinInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setURLAddinInfo(String value) {
                this.urlAddinInfo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="GroupSignatures" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Certificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="9"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="numberGroup" use="required">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "groupSignatures"
            })
            public static class CustomerSignature {

                @XmlElement(name = "GroupSignatures", required = true)
                protected List<Settings.Data.CryptoParameters.CustomerSignature.GroupSignatures> groupSignatures;

                /**
                 * Gets the value of the groupSignatures property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the groupSignatures property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getGroupSignatures().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Settings.Data.CryptoParameters.CustomerSignature.GroupSignatures }
                 * 
                 * 
                 */
                public List<Settings.Data.CryptoParameters.CustomerSignature.GroupSignatures> getGroupSignatures() {
                    if (groupSignatures == null) {
                        groupSignatures = new ArrayList<Settings.Data.CryptoParameters.CustomerSignature.GroupSignatures>();
                    }
                    return this.groupSignatures;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Certificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="9"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="numberGroup" use="required">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "certificate"
                })
                public static class GroupSignatures {

                    @XmlElement(name = "Certificate", required = true)
                    protected List<byte[]> certificate;
                    @XmlAttribute(name = "numberGroup", required = true)
                    protected BigInteger numberGroup;

                    /**
                     * Gets the value of the certificate property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the certificate property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getCertificate().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * byte[]
                     * 
                     */
                    public List<byte[]> getCertificate() {
                        if (certificate == null) {
                            certificate = new ArrayList<byte[]>();
                        }
                        return this.certificate;
                    }

                    /**
                     * Gets the value of the numberGroup property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getNumberGroup() {
                        return numberGroup;
                    }

                    /**
                     * Sets the value of the numberGroup property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setNumberGroup(BigInteger value) {
                        this.numberGroup = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="EncryptAlgorithm">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="50"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "encryptAlgorithm"
            })
            public static class Encrypted {

                @XmlElement(name = "EncryptAlgorithm", required = true)
                protected String encryptAlgorithm;

                /**
                 * Gets the value of the encryptAlgorithm property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEncryptAlgorithm() {
                    return encryptAlgorithm;
                }

                /**
                 * Sets the value of the encryptAlgorithm property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEncryptAlgorithm(String value) {
                    this.encryptAlgorithm = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Signed" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RuleSignatures">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="docKind" use="required" type="{http://directbank.1c.ru/XMLSchema}DocKindType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "signed"
        })
        public static class Document {

            @XmlElement(name = "Signed")
            protected Settings.Data.Document.Signed signed;
            @XmlAttribute(name = "docKind", required = true)
            protected String docKind;

            /**
             * Gets the value of the signed property.
             * 
             * @return
             *     possible object is
             *     {@link Settings.Data.Document.Signed }
             *     
             */
            public Settings.Data.Document.Signed getSigned() {
                return signed;
            }

            /**
             * Sets the value of the signed property.
             * 
             * @param value
             *     allowed object is
             *     {@link Settings.Data.Document.Signed }
             *     
             */
            public void setSigned(Settings.Data.Document.Signed value) {
                this.signed = value;
            }

            /**
             * Gets the value of the docKind property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDocKind() {
                return docKind;
            }

            /**
             * Sets the value of the docKind property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDocKind(String value) {
                this.docKind = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RuleSignatures">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ruleSignatures"
            })
            public static class Signed {

                @XmlElement(name = "RuleSignatures", required = true)
                protected String ruleSignatures;

                /**
                 * Gets the value of the ruleSignatures property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRuleSignatures() {
                    return ruleSignatures;
                }

                /**
                 * Sets the value of the ruleSignatures property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRuleSignatures(String value) {
                    this.ruleSignatures = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="Login">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="User">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="50"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Certificate">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="EncryptingAlgorithm">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="50"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "login",
            "certificate"
        })
        public static class Logon {

            @XmlElement(name = "Login")
            protected Settings.Data.Logon.Login login;
            @XmlElement(name = "Certificate")
            protected Settings.Data.Logon.Certificate certificate;

            /**
             * Gets the value of the login property.
             * 
             * @return
             *     possible object is
             *     {@link Settings.Data.Logon.Login }
             *     
             */
            public Settings.Data.Logon.Login getLogin() {
                return login;
            }

            /**
             * Sets the value of the login property.
             * 
             * @param value
             *     allowed object is
             *     {@link Settings.Data.Logon.Login }
             *     
             */
            public void setLogin(Settings.Data.Logon.Login value) {
                this.login = value;
            }

            /**
             * Gets the value of the certificate property.
             * 
             * @return
             *     possible object is
             *     {@link Settings.Data.Logon.Certificate }
             *     
             */
            public Settings.Data.Logon.Certificate getCertificate() {
                return certificate;
            }

            /**
             * Sets the value of the certificate property.
             * 
             * @param value
             *     allowed object is
             *     {@link Settings.Data.Logon.Certificate }
             *     
             */
            public void setCertificate(Settings.Data.Logon.Certificate value) {
                this.certificate = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="EncryptingAlgorithm">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="50"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "encryptingAlgorithm"
            })
            public static class Certificate {

                @XmlElement(name = "EncryptingAlgorithm", required = true)
                protected String encryptingAlgorithm;

                /**
                 * Gets the value of the encryptingAlgorithm property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEncryptingAlgorithm() {
                    return encryptingAlgorithm;
                }

                /**
                 * Sets the value of the encryptingAlgorithm property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEncryptingAlgorithm(String value) {
                    this.encryptingAlgorithm = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="User">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="50"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "user"
            })
            public static class Login {

                @XmlElement(name = "User", required = true)
                protected String user;

                /**
                 * Gets the value of the user property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUser() {
                    return user;
                }

                /**
                 * Sets the value of the user property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUser(String value) {
                    this.user = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Login">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Instructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "login",
            "instructions"
        })
        public static class ReceiptStatement {

            @XmlElement(name = "Login", required = true)
            protected String login;
            @XmlElement(name = "Instructions", required = true)
            protected String instructions;

            /**
             * Gets the value of the login property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLogin() {
                return login;
            }

            /**
             * Sets the value of the login property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLogin(String value) {
                this.login = value;
            }

            /**
             * Gets the value of the instructions property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInstructions() {
                return instructions;
            }

            /**
             * Sets the value of the instructions property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInstructions(String value) {
                this.instructions = value;
            }

        }

    }

}
