//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 02:20:56 PM EET 
//


package ru.openbank.marketplace.front.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuccessResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuccessResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="SendPacketResponse" type="{http://directbank.1c.ru/XMLSchema}SendPacketResponseType"/>
 *         &lt;element name="GetPacketListResponse" type="{http://directbank.1c.ru/XMLSchema}GetPacketListResponseType"/>
 *         &lt;element name="GetPacketResponse" type="{http://directbank.1c.ru/XMLSchema}Packet"/>
 *         &lt;element name="LogonResponse" type="{http://directbank.1c.ru/XMLSchema}LogonResponseType"/>
 *         &lt;element name="LogonCertResponse" type="{http://directbank.1c.ru/XMLSchema}LogonCertResponseType"/>
 *         &lt;element name="GetSettingsResponse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://directbank.1c.ru/XMLSchema}GetSettingsResponseType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuccessResultType", propOrder = {
    "sendPacketResponse",
    "getPacketListResponse",
    "getPacketResponse",
    "logonResponse",
    "logonCertResponse",
    "getSettingsResponse"
})
public class SuccessResultType {

    @XmlElement(name = "SendPacketResponse")
    protected SendPacketResponseType sendPacketResponse;
    @XmlElement(name = "GetPacketListResponse")
    protected GetPacketListResponseType getPacketListResponse;
    @XmlElement(name = "GetPacketResponse")
    protected Packet getPacketResponse;
    @XmlElement(name = "LogonResponse")
    protected LogonResponseType logonResponse;
    @XmlElement(name = "LogonCertResponse")
    protected LogonCertResponseType logonCertResponse;
    @XmlElement(name = "GetSettingsResponse")
    protected SuccessResultType.GetSettingsResponse getSettingsResponse;

    /**
     * Gets the value of the sendPacketResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SendPacketResponseType }
     *     
     */
    public SendPacketResponseType getSendPacketResponse() {
        return sendPacketResponse;
    }

    /**
     * Sets the value of the sendPacketResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendPacketResponseType }
     *     
     */
    public void setSendPacketResponse(SendPacketResponseType value) {
        this.sendPacketResponse = value;
    }

    /**
     * Gets the value of the getPacketListResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetPacketListResponseType }
     *     
     */
    public GetPacketListResponseType getGetPacketListResponse() {
        return getPacketListResponse;
    }

    /**
     * Sets the value of the getPacketListResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPacketListResponseType }
     *     
     */
    public void setGetPacketListResponse(GetPacketListResponseType value) {
        this.getPacketListResponse = value;
    }

    /**
     * Gets the value of the getPacketResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Packet }
     *     
     */
    public Packet getGetPacketResponse() {
        return getPacketResponse;
    }

    /**
     * Sets the value of the getPacketResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packet }
     *     
     */
    public void setGetPacketResponse(Packet value) {
        this.getPacketResponse = value;
    }

    /**
     * Gets the value of the logonResponse property.
     * 
     * @return
     *     possible object is
     *     {@link LogonResponseType }
     *     
     */
    public LogonResponseType getLogonResponse() {
        return logonResponse;
    }

    /**
     * Sets the value of the logonResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogonResponseType }
     *     
     */
    public void setLogonResponse(LogonResponseType value) {
        this.logonResponse = value;
    }

    /**
     * Gets the value of the logonCertResponse property.
     * 
     * @return
     *     possible object is
     *     {@link LogonCertResponseType }
     *     
     */
    public LogonCertResponseType getLogonCertResponse() {
        return logonCertResponse;
    }

    /**
     * Sets the value of the logonCertResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogonCertResponseType }
     *     
     */
    public void setLogonCertResponse(LogonCertResponseType value) {
        this.logonCertResponse = value;
    }

    /**
     * Gets the value of the getSettingsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessResultType.GetSettingsResponse }
     *     
     */
    public SuccessResultType.GetSettingsResponse getGetSettingsResponse() {
        return getSettingsResponse;
    }

    /**
     * Sets the value of the getSettingsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessResultType.GetSettingsResponse }
     *     
     */
    public void setGetSettingsResponse(SuccessResultType.GetSettingsResponse value) {
        this.getSettingsResponse = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://directbank.1c.ru/XMLSchema}GetSettingsResponseType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class GetSettingsResponse
        extends GetSettingsResponseType
    {


    }

}
